### ISSUE TITLE
AAAAH!!!

### ISSUE THREAD

**Issue by frickypickle** [Gameman2110/Kahoot-Bot#2]
node:internal/modules/cjs/loader:927
  throw err;
  ^

Error: Cannot find module 'C:\Windows\system32\bot.js'
←[90m    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:924:15)←[39m
←[90m    at Function.Module._load (node:internal/modules/cjs/loader:769:27)←[39m
←[90m    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)←[39m
←[90m    at node:internal/main/run_main_module:17:47←[39m {
  code: ←[32m'MODULE_NOT_FOUND'←[39m,
  requireStack: []
}

**Comment by ThunbergOlle** [comment]
That's not how you write an issue
